export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE_NETWORK = 'AUTHENTICATION_FAILURE_NETWORK';
export const AUTHENTICATION_FAILURE_VALIDATION = 'AUTHENTICATION_FAILURE_VALIDATION';
export const AUTHENTICATION_DEFAULT = 'AUTHENTICATION_DEFAULT';
export const AUTHENTICATION_RESET = 'AUTHENTICATION_RESET';

export const LOGOUT_DEFAULT = 'LOGOUT_DEFAULT';
export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE_NETWORK = 'LOGOUT_FAILURE_NETWORK';
export const LOGOUT_FAILURE_VALIDATION = 'LOGOUT_FAILURE_VALIDATION';

export const GET_PROFILE_DEFAULT = 'GET_PROFILE_DEFAULT';
export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE_NETWORK = 'GET_PROFILE_FAILURE_NETWORK';
export const GET_PROFILE_FAILURE_VALIDATION = 'GET_PROFILE_FAILURE_VALIDATION';

export const CHARGE_BALANCE_DEFAULT = 'CHARGE_BALANCE_DEFAULT';
export const CHARGE_BALANCE_STARTED = 'CHARGE_BALANCE_STARTED';
export const CHARGE_BALANCE_SUCCESS = 'CHARGE_BALANCE_SUCCESS';
export const CHARGE_BALANCE_FAILURE_NETWORK = 'CHARGE_BALANCE_FAILURE_NETWORK';
export const CHARGE_BALANCE_FAILURE_VALIDATION = 'CHARGE_BALANCE_FAILURE_VALIDATION';

export const PURCHASE_DEFAULT = 'PURCHASE_DEFAULT';
export const PURCHASE_STARTED = 'PURCHASE_STARTED';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILURE_NETWORK = 'PURCHASE_FAILURE_NETWORK';
export const PURCHASE_FAILURE_VALIDATION = 'PURCHASE_FAILURE_VALIDATION';

export const HANDLE_WISHLIST_DEFAULT = 'HANDLE_WISHLIST_DEFAULT';
export const HANDLE_WISHLIST_STARTED = 'HANDLE_WISHLIST_STARTED';
export const HANDLE_WISHLIST_SUCCESS = 'HANDLE_WISHLIST_SUCCESS';
export const HANDLE_WISHLIST_FAILURE_NETWORK = 'HANDLE_WISHLIST_FAILURE_NETWORK';
export const HANDLE_WISHLIST_FAILURE_VALIDATION = 'HANDLE_WISHLIST_FAILURE_VALIDATION';

export const HANDLE_WISHED_BOOKS = 'HANDLE_WISHED_BOOKS';

export const GET_ALL_BOOKS_DEFAULT = 'GET_ALL_BOOKS_DEFAULT';
export const GET_ALL_BOOKS_STARTED = 'GET_ALL_BOOKS_STARTED';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAILURE_NETWORK = 'GET_ALL_BOOKS_FAILURE_NETWORK';
export const GET_ALL_BOOKS_FAILURE_VALIDATION = 'GET_ALL_BOOKS_FAILURE_VALIDATION';

export const GET_SCROLLABLE_BOOKS_DEFAULT = 'GET_SCROLLABLE_BOOKS_DEFAULT';
export const GET_SCROLLABLE_BOOKS_STARTED = 'GET_SCROLLABLE_BOOKS_STARTED';
export const GET_SCROLLABLE_BOOKS_SUCCESS = 'GET_SCROLLABLE_BOOKS_SUCCESS';
export const GET_SCROLLABLE_BOOKS_FAILURE_NETWORK = 'GET_SCROLLABLE_BOOKS_FAILURE_NETWORK';
export const GET_SCROLLABLE_BOOKS_FAILURE_VALIDATION = 'GET_SCROLLABLE_BOOKS_FAILURE_VALIDATION';

export const GET_BOOKS_IDS_DEFAULT = 'GET_BOOKS_IDS_DEFAULT';
export const GET_BOOKS_IDS_STARTED = 'GET_BOOKS_IDS_STARTED';
export const GET_BOOKS_IDS_SUCCESS = 'GET_BOOKS_IDS_SUCCESS';
export const GET_BOOKS_IDS_FAILURE_NETWORK = 'GET_BOOKS_IDS_FAILURE_NETWORK';
export const GET_BOOKS_IDS_FAILURE_VALIDATION = 'GET_BOOKS_IDS_FAILURE_VALIDATION';

export const SEARCH_DEFAULT = 'SEARCH_DEFAULT';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE_NETWORK = 'SEARCH_FAILURE_NETWORK';
export const SEARCH_FAILURE_VALIDATION = 'SEARCH_FAILURE_VALIDATION';