export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE_NETWORK = 'AUTHENTICATION_FAILURE_NETWORK';
export const AUTHENTICATION_FAILURE_VALIDATION = 'AUTHENTICATION_FAILURE_VALIDATION';
export const AUTHENTICATION_DEFAULT = 'AUTHENTICATION_DEFAULT';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE_NETWORK = 'LOGIN_FAILURE_NETWORK';
export const LOGIN_FAILURE_VALIDATION = 'LOGIN_FAILURE_VALIDATION';
export const LOGIN_DEFAULT = 'LOGIN_DEFAULT';