export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE_NETWORK = 'AUTHENTICATION_FAILURE_NETWORK';
export const AUTHENTICATION_FAILURE_VALIDATION = 'AUTHENTICATION_FAILURE_VALIDATION';
export const AUTHENTICATION_DEFAULT = 'AUTHENTICATION_DEFAULT';
export const AUTHENTICATION_RESET = 'AUTHENTICATION_RESET';


export const GET_PROFILE_DEFAULT = 'GET_PROFILE_DEFAULT';
export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE_NETWORK = 'GET_PROFILE_FAILURE_NETWORK';
export const GET_PROFILE_FAILURE_VALIDATION = 'GET_PROFILE_FAILURE_VALIDATION';